version: 2
jobs:
  build:
    working_directory: ~/circleci-gaji-site
    docker:
      - image: circleci/node:10.13.0-stretch
    steps:
      - run:
          name: Setup nvm and npm
          command: |
            wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            export NVM_DIR=$HOME/.nvm
            touch $HOME/.nvmrc
            source $NVM_DIR/nvm.sh
            nvm install 10.13.0 && nvm alias default 10.13.0
            echo 10.13.0 > $HOME/.nvmrc
            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
            npm install -g yarn
      - checkout
      - restore_cache:
          name: Restore npm packages cache
          keys:
            - npm-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save npm packages cache
          key: npm-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test
      - run: yarn lint
