version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "develop"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
